### PR TITLE
Allow admin to define the internal term representation

### PR DESCRIPTION
**Pull request by abias**
Before this patch, the internal representation of the terms (as they are stored in the Moodle database) was hardcoded to ST = 0 and WT = 1.
This was a problem if you wanted to integrate Moodle with an external lecture management system which uses a different representation of ST = 1 and WT = 2 and wanted to fill the cust
    
This patch adds an admin settings which lets the admin control how the terms are represented internally.
Currently, it just has to options (ST = 0 / WT = 1 and ST = 1 / WT = 2), but the code is prepared to add additional options to the admin setting as well as add the possibility to con
    
This implementation does _not_ update existing field values when the setting is changed. The admin will have to consider a switch of the representation carefully.

----

Please note that this PR is based on #6 as both create a settings.php file.
It should be reviewed and merged after #6.

### CODE REVIEW

**Comment by NinaHerrmann** [comment]
Hey @abias, sorry for the late feedback for all the pull requests you are making. As this pull request includes all of the features you are implementing it would be either easier to state all features here and delete the other pull requests or make separate branches for all of them. (I think the first one makes more sense for this case). 
Thanks in advance!

**Comment by abias** [comment]
Hi @NinaHerrmann ,

> sorry for the late feedback for all the pull requests you are making. 

No worries.

> As this pull request includes all of the features you are implementing it would be either easier to state all features here and delete the other pull requests or make separate branches for all of them. (I think the first one makes more sense for this case).

I didn't make independent branches for all three improvements as all of them create a settings.php and touch the same files, thus I wanted to avoid having much work to rebase them as soon as you have merged one of them.

If you are 100% happy with all developments, it should be fine just to merge this PR here and close the other ones as unmerged but done.

But if you have any change requests, you should work through the PRs individually starting from #5 and I will rebase the following ones as soon as the earlier ones are merged.

Thanks in advance!

Cheers,
Alex

**Comment by NinaHerrmann** [comment]
Hey @abias,
I merged it by accident, checking out the wrong branch, but I will test it and provide Feedback as soon as I can.

**Comment by abias** [comment]
Hey @NinaHerrmann ,

> I merged it by accident, checking out the wrong branch, but I will test it and provide Feedback as soon as I can.

do you have any news about this PR which you accidently merged and then reverted? Shall I resubmit it so that it does not get lost in your review queue?

**Pull request merged**
